# The base URL for your site. Should include the protocol (e.g., 'https://').
baseURL = 'https://sleekstream.netlify.app'
# The title of your site.
title = 'Sleek Stream'
# The default language code for your site.
languageCode = "en-us"
